SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE VIEW [dbo].[listaCliente]
AS
select CLIENTE.IDCLI, CLIENTE.NOMAPECLI, CLIENTE.DIRCLI, CLIENTE.CELCLI, CLIENTE.ESTCLI FROM cliente
INNER JOIN DETALLE_PEDIDO ON DETALLE_PEDIDO.IDDETENV = CLIENTE.IDDETENV WHERE CLIENTE.IDCLI = 'A'
GO
