SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
create view [dbo].[LISTARPRODUCTO]
as
select PRODUCTO.IDPROD, PRODUCTO.NOMPRO, PRODUCTO.PREPRO, PRODUCTO.DESPRO, PRODUCTO.ESTPRO , CATEGORIA.DESCAT, CATEGORIA.IDCAT, CATEGORIA.NOMCAT FROM PRODUCTO
INNER JOIN PEDIDO ON PRODUCTO.IDPROD = PRODUCTO.IDPROD
INNER JOIN CATEGORIA ON CATEGORIA.IDCAT = CATEGORIA.IDCAT WHERE PRODUCTO.ESTPRO = 'A'
GO
