SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
create view [dbo].[listarPedido]
AS 
SELECT CLIENTE.IDCLI, CLIENTE.NOMAPECLI , PRODUCTO.IDPROD , PRODUCTO.DESPRO, DETALLE_PEDIDO.CODENV, DETALLE_PEDIDO.FECENV ,DETALLE_PEDIDO.DETPED, DETALLE_PEDIDO.ESTDE FROM DETALLE_PEDIDO
INNER JOIN CLIENTE ON CLIENTE.IDCLI = DETALLE_PEDIDO.IDPED
INNER JOIN PRODUCTO ON PRODUCTO.IDPROD = PRODUCTO.IDPROD WHERE DETALLE_PEDIDO.ESTDE = 'A' 
GO
