SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[RegristrarPEDIDO]
@CANTPED CHAR(1),
@PRECIO MONEY,
@ESTADO CHAR(1)
AS
INSERT INTO PEDIDO (CANTPED, PREPED, ESTPE)
VALUES('CANTIDAD', @PRECIO, @ESTADO)
GO
