CREATE TABLE [dbo].[PEDIDO]
(
[IDPED] [int] NOT NULL,
[CANTPED] [int] NOT NULL,
[PREPED] [money] NOT NULL,
[ESTPE] [char] (1) COLLATE Modern_Spanish_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PEDIDO] ADD CONSTRAINT [PEDIDO_pk] PRIMARY KEY CLUSTERED  ([IDPED]) ON [PRIMARY]
GO
