CREATE TABLE [dbo].[CLIENTE]
(
[IDCLI] [int] NOT NULL IDENTITY(1, 1),
[NOMAPECLI] [varchar] (30) COLLATE Modern_Spanish_CI_AS NOT NULL,
[DIRCLI] [varchar] (20) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CORCLI] [varchar] (20) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CELCLI] [char] (9) COLLATE Modern_Spanish_CI_AS NOT NULL,
[ESTCLI] [char] (1) COLLATE Modern_Spanish_CI_AS NOT NULL,
[IDDETENV] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CLIENTE] ADD CONSTRAINT [CLIENTE_pk] PRIMARY KEY CLUSTERED  ([IDCLI]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CLIENTE] ADD CONSTRAINT [CLIENTE_DETALLE_PEDIDO] FOREIGN KEY ([IDDETENV]) REFERENCES [dbo].[DETALLE_PEDIDO] ([IDDETENV])
GO
