CREATE TABLE [dbo].[PROVEEDOR]
(
[IDPRO] [int] NOT NULL,
[NOMPRO] [varchar] (20) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CONTPRO] [varchar] (30) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CORPRO] [varchar] (30) COLLATE Modern_Spanish_CI_AS NOT NULL,
[DIRPRO] [varchar] (20) COLLATE Modern_Spanish_CI_AS NOT NULL,
[TELPRO] [char] (9) COLLATE Modern_Spanish_CI_AS NOT NULL,
[RUC] [char] (11) COLLATE Modern_Spanish_CI_AS NOT NULL,
[SUCPRO] [varchar] (20) COLLATE Modern_Spanish_CI_AS NOT NULL,
[ESTPRO] [char] (1) COLLATE Modern_Spanish_CI_AS NOT NULL,
[IDPROD] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PROVEEDOR] ADD CONSTRAINT [PROVEEDOR_pk] PRIMARY KEY CLUSTERED  ([IDPRO]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PROVEEDOR] ADD CONSTRAINT [PROVEEDOR_PRODUCTO] FOREIGN KEY ([IDPROD]) REFERENCES [dbo].[PRODUCTO] ([IDPROD])
GO
