CREATE TABLE [dbo].[DETALLE_PEDIDO]
(
[IDDETENV] [int] NOT NULL,
[CODENV] [char] (5) COLLATE Modern_Spanish_CI_AS NOT NULL,
[DETPED] [varchar] (50) COLLATE Modern_Spanish_CI_AS NOT NULL,
[FECORD] [datetime] NOT NULL,
[FECENV] [datetime] NOT NULL,
[ESTDE] [char] (1) COLLATE Modern_Spanish_CI_AS NOT NULL,
[IDPED] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DETALLE_PEDIDO] ADD CONSTRAINT [DETALLE_PEDIDO_pk] PRIMARY KEY CLUSTERED  ([IDDETENV]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DETALLE_PEDIDO] ADD CONSTRAINT [DETALLE_PEDIDO_PEDIDO] FOREIGN KEY ([IDPED]) REFERENCES [dbo].[PEDIDO] ([IDPED])
GO
