CREATE TABLE [dbo].[CATEGORIA]
(
[IDCAT] [int] NOT NULL,
[NOMCAT] [varchar] (15) COLLATE Modern_Spanish_CI_AS NOT NULL,
[DESCAT] [varchar] (50) COLLATE Modern_Spanish_CI_AS NOT NULL,
[ESTACA] [char] (1) COLLATE Modern_Spanish_CI_AS NOT NULL,
[IDPRO] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CATEGORIA] ADD CONSTRAINT [CATEGORIA_pk] PRIMARY KEY CLUSTERED  ([IDCAT]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CATEGORIA] ADD CONSTRAINT [CATEGORIA_PRODUCTO] FOREIGN KEY ([IDPRO]) REFERENCES [dbo].[PRODUCTO] ([IDPROD])
GO
