CREATE TABLE [dbo].[PRODUCTO]
(
[IDPROD] [int] NOT NULL IDENTITY(1, 1),
[NOMPRO] [varchar] (15) COLLATE Modern_Spanish_CI_AS NOT NULL,
[DESPRO] [varchar] (50) COLLATE Modern_Spanish_CI_AS NOT NULL,
[PREPRO] [money] NOT NULL,
[ESTPRO] [char] (1) COLLATE Modern_Spanish_CI_AS NOT NULL,
[IDPED] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PRODUCTO] ADD CONSTRAINT [PRODUCTO_pk] PRIMARY KEY CLUSTERED  ([IDPROD]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PRODUCTO] ADD CONSTRAINT [PRODUCTO_PEDIDO] FOREIGN KEY ([IDPED]) REFERENCES [dbo].[PEDIDO] ([IDPED])
GO
