CREATE TABLE [dbo].[USUARIO]
(
[IDUSU] [int] NOT NULL,
[NOMAPEUSU] [varchar] (20) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CORUSU] [varchar] (15) COLLATE Modern_Spanish_CI_AS NOT NULL,
[DIRUSU] [varchar] (15) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CELUSU] [char] (12) COLLATE Modern_Spanish_CI_AS NOT NULL,
[DNIUSU] [char] (12) COLLATE Modern_Spanish_CI_AS NOT NULL,
[FECCON] [date] NOT NULL,
[ESTUSU] [char] (1) COLLATE Modern_Spanish_CI_AS NOT NULL,
[IDDETENV] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[USUARIO] ADD CONSTRAINT [USUARIO_pk] PRIMARY KEY CLUSTERED  ([IDUSU]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[USUARIO] ADD CONSTRAINT [Usuario_DETALLE_PEDIDO] FOREIGN KEY ([IDDETENV]) REFERENCES [dbo].[DETALLE_PEDIDO] ([IDDETENV])
GO
