CREATE TABLE [dbo].[CARGADOR]
(
[IDCAR] [int] NOT NULL,
[NOMCAR] [varchar] (15) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CELCAR] [char] (9) COLLATE Modern_Spanish_CI_AS NOT NULL,
[ESTCAR] [char] (1) COLLATE Modern_Spanish_CI_AS NOT NULL,
[IDDETENV] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CARGADOR] ADD CONSTRAINT [CARGADOR_pk] PRIMARY KEY CLUSTERED  ([IDCAR]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CARGADOR] ADD CONSTRAINT [CARGADOR_DETALLE_PEDIDO] FOREIGN KEY ([IDDETENV]) REFERENCES [dbo].[DETALLE_PEDIDO] ([IDDETENV])
GO
